apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coinbase-demo #cluster name
  region: us-east-1 #desired region

nodeGroups:
  - name: ng-1 #cluster node group name
    instanceType: t3.medium #desired instance type
    desiredCapacity: 2 #desired nodes count / capacity
    ssh:
      allow: false