apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: coinbase-demo
    app.kubernetes.io/instance: coinbase-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: coinbase-qa
spec:
  selector:
    app: coinbase-qa
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000
      